# This is a basic workflow to help you get started with Actions

name: CI for Login

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      job_name:
        description: 'Run Job'
        required: true
        default: 'build_deploy'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Npm install packages
        run: npm install
        
      - name: Test & Code Coverage
        run: npm test -- --coverage
        
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}
        
      - name: Build package
        env:
          CI: false
        run: npm run build
        
      - name: Checkout code
        uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Set up Docker Buildx
#         id: buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Build and push docker image
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           context: ./
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKER_USERNAME }}/fitbuddyf.cicd
